branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: dependencies
    prefix: dependencyupdate/
  - label: '*'
    prefix: issues/
branchName: '${issue.number}'
