on: [push]

jobs:
  greet_log_job:
    runs-on: ubuntu-latest
    name: Log Main Event
    steps:
    - name: Log Step
      id: greet-log-step
      uses: napagroup/grape-ui-react/.github/actions/log-github@devops/41
      with:
        who-to-greet: 'User'
    - name: Time of log
      run: echo "The time was ${{ steps.greet.outputs.time }}"
  prod_build_job:
    runs-on: ubuntu-latest
    name: Build packages for prod repo
    env:
      SOURCE_REPO: napagroup/grape-ui-react
      TARGET_REPO: napagroup/grape-ui-marketing
      SOURCE_REPO_PATH: source
      TARGET_REPO_PATH: target
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Confirm node and env vars
      run: |
        node -v
        npm -v
        echo '$GITHUB_WORKSPACE' $GITHUB_WORKSPACE
        echo '$SOURCE_REPO_PATH' $SOURCE_REPO_PATH
        echo '$TARGET_REPO_PATH' $TARGET_REPO_PATH
        pwd
        ls -li
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        repository: ${{ env.SOURCE_REPO }}
        path: $GITHUB_WORKSPACE
    - name: Confirm source checkout
      run: |
        ls -li
    - name: Install and Build source repo
      run: |
        npm install
        npm run build
        ls -li


